Finish hopefully
rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

diff --git a/task/deploy-and-test.yaml b/task/deploy-and-test.yaml
--- a/task/deploy-and-test.yaml
+++ b/task/deploy-and-test.yaml
@@ -14,7 +14,7 @@ spec:
         secretName: $(params.rhdh_secrets)
   steps:
     - name: deploy-and-test
-      image: quay.io/redhat-user-workloads/rh-ee-oaljalju-tenant/test2:c5ede9a7b2caa42e32f745bea5b2c96d942cd06c
+      image: quay.io/redhat-user-workloads/rh-ee-oaljalju-tenant/test2:5bca399965bf7bebe60d7739ccaecbf46ad60e60 # Container image with OC installed
       volumeMounts:
         - mountPath: "/etc/secrets"
           name: $(params.rhdh_secrets)
@@ -29,12 +29,63 @@ spec:
         WORKSPACE=$(pwd)
         cd /tmp || exit
 
+
+        check_backstage_running() {
+          local release_name=$1
+          local namespace=$2
+          local url=$3
+
+          local max_attempts=30
+          local wait_seconds=30
+
+          echo "Checking if Backstage is up and running at ${url}"
+
+          for ((i = 1; i <= max_attempts; i++)); do
+            local http_status
+            http_status=$(curl --insecure -I -s "${url}" | grep HTTP | awk '{print $2}')
+
+            if [ "${http_status}" -eq 200 ]; then
+              echo "Backstage is up and running!"
+              export BASE_URL="${url}"
+              echo "######## BASE URL ########"
+              echo "${BASE_URL}"
+              return 0
+            else
+              echo "Attempt ${i} of ${max_attempts}: Backstage not yet available (HTTP Status: ${http_status})"
+              sleep "${wait_seconds}"
+            fi
+          done
+
+          echo "Failed to reach Backstage at ${BASE_URL} after ${max_attempts} attempts." | tee -a "/tmp/${LOGFILE}"
+          return 1
+        }
+
         API_SERVER_URL=$(cat /etc/secrets/API_SERVER_URL)
         USERNAME=$(cat /etc/secrets/USERNAME)
         PASSWORD=$(cat /etc/secrets/PASSWORD)
         oc login ${API_SERVER_URL} --username=${USERNAME} --password=${PASSWORD}
-        oc whoami --show-console
-        # curl -sSLO https://raw.githubusercontent.com/rhdh-bot/openshift-helm-charts/redhat-developer-hub-1.2-150-CI/installation/install.sh && chmod +x install.sh
-        # ./install.sh 1.2-150-CI --namespace showcase --chartrepo
+
+        oc create ns showcase
+        export BASE_URL="redhat-developer-hub-showcase.$(oc get ingresses.config/cluster -o jsonpath='{.spec.domain}')"
+
+        echo "Installing Helm 3 client"
+        mkdir ~/tmpbin && cd ~/tmpbin
+        curl -sL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash -f
+        export PATH=$(pwd):$PATH
+        echo "Helm client installed successfully."
+        
+        curl -sSLO https://raw.githubusercontent.com/rhdh-bot/openshift-helm-charts/redhat-developer-hub-1.3-124-CI/installation/install.sh && chmod +x install.sh
+        ./install.sh 1.3-124-CI --namespace showcase --chartrepo
+
+        check_backstage_running redhat-developer-hub showcase ${BASE_URL}
+        git clone https://github.com/Omar-AlJaljuli/janus-idp-backstage-showcase-.git
+        cd janus-idp-backstage-showcase- || exit
+        git checkout "Konflux-CI" || exit
+        cd e2e-tests/
+        yarn install
+        yarn playwright install
+        
+        cd playwright/e2e/
+        yarn playwright test ./instance-health-check.spec.ts
         
 
